### ISSUE TITLE
Tons of warnings in console when running npm run dev

### ISSUE THREAD

**Issue by curtisblackwell** [vuejs-templates/webpack-simple#9]
```
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
```

I just installed this and updated vue `npm i -D vue`.

I get 96 of these warnings. It makes trying to find stuff I log to the console frustrating.

`Vue@v1.0.20`, in case that makes any difference.

**Comment by yyx990803** [comment]
Should be fixed now.

**Comment by bochen2014** [comment]
i'm running vue@1.0.28 and still having the same issue. 
my first vue journey isn't as smooth as I have expected!    :joy: :joy:

@yyx990803 take a look at https://github.com/bochen2014/vue.js
the project is actually created by webpackbin, it works great in webpackbin, after after I downloaded localy, it stops working.  All i get is a blank page, with chrome warning like the issue tiltle says, which I don't understand why

thanks!
